name: Deploy Mezon FE Prod
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: mezon-fe-prod
    name: Build Mezon FE
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Environments"
          echo "NODE_ENV: ${{ env.NODE_ENV }}"
          echo "Node version: $(node -v)"
          echo "Installing dependencies"
          source ~/.bashrc
          yarn
      - name: Build
        run: |
          echo "Build"
          rm apps/chat/.env
          mv apps/chat/prod.env apps/chat/.env
          yarn build:chat

  deploy:
    runs-on: mezon-fe-prod
    name: Deploy Mezon FE
    environment: prod
    needs:
      - build
    steps:
      - name: Clear www folder
        run: |
          echo "Clearing /var/www/mezon-fe/"
          rm -rf /var/www/mezon-fe/*

      - name: Copy files to www
        run: |
          echo "Copying files to /var/www/mezon-fe/"
          cp -r ./dist/apps/chat/* /var/www/mezon-fe/
