name: Deploy Mezon FE Dev
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: mezone-fe-dev
    name: Build Mezon FE
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "Environments"
          echo "NODE_ENV: ${{ env.NODE_ENV }}"
          export nv=$(node -v)
          echo "Node version: $nv"
          echo "Installing dependencies"
          yarn config set nodedir ~/.cache/node-gyp/"${nv:1}"
          echo "Node directory: ${nv:1}"
          source ~/.bashrc
          yarn
      - name: Build
        run: |
          echo "Build"
          yarn build:chat

  deploy:
    runs-on: mezone-fe-dev
    name: Deploy Mezon FE
    environment: dev
    needs:
      - build
    steps:
      - name: Clear www folder
        run: |
          echo "Clearing /var/www/mezon/"
          rm -rf /var/www/mezon/*

      - name: Copy files to www
        run: |
          echo "Copying files to /var/www/mezon/"
          cp -r ./dist/apps/chat/* /var/www/mezon/
