name: Deploy Mezon FE Prod
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: mezone-fe-dev
    name: Build Mezon FE
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Environments"
          echo "NODE_ENV: ${{ env.NODE_ENV }}"
          export nv=$(node -v)
          echo "Node version: $nv"
          echo "Installing dependencies"
          yarn config set nodedir ~/.cache/node-gyp/"${nv:1}"
          echo "Node directory: ${nv:1}"
          source ~/.bashrc
          yarn
      - name: Build
        run: |
          echo "Build"
          rm -rf apps/chat/.env
          mv apps/chat/.env.prod apps/chat/.env
          yarn build:chat
        env:
          NX_CHAT_APP_API_HOST: ${{ secrets.NX_CHAT_APP_API_HOST_PROD }}
          NX_CHAT_APP_API_PORT: ${{ secrets.NX_CHAT_APP_API_PORT_PROD }}
          NX_CHAT_APP_API_KEY: ${{ secrets.NX_CHAT_APP_API_KEY_PROD }}
          NX_CHAT_APP_API_SECURE: ${{ secrets.NX_CHAT_APP_API_SECURE_PROD }}
          NX_CHAT_APP_GOOGLE_CLIENT_ID: ${{ secrets.NX_CHAT_APP_GOOGLE_CLIENT_ID_PROD }}
          NX_CHAT_APP_REDIRECT_URI: ${{ secrets.NX_CHAT_APP_REDIRECT_URI_PROD }}
          NX_CHAT_APP_FCM_API_KEY: ${{ secrets.NX_CHAT_APP_FCM_API_KEY_PROD }}
          NX_CHAT_APP_FCM_AUTH_DOMAIN: ${{ secrets.NX_CHAT_APP_FCM_AUTH_DOMAIN_PROD }}
          NX_CHAT_APP_FCM_PROJECT_ID: ${{ secrets.NX_CHAT_APP_FCM_PROJECT_ID_PROD }}
          NX_CHAT_APP_FCM_STORAGE_BUCKET: ${{ secrets.NX_CHAT_APP_FCM_STORAGE_BUCKET_PROD }}
          NX_CHAT_APP_FCM_MESSAGING_SENDER_ID: ${{ secrets.NX_CHAT_APP_FCM_MESSAGING_SENDER_ID_PROD }}
          NX_CHAT_APP_FCM_APP_ID: ${{ secrets.NX_CHAT_APP_FCM_APP_ID_PROD }}
          NX_CHAT_APP_FCM_MEASUREMENT_ID: ${{ secrets.NX_CHAT_APP_FCM_MEASUREMENT_ID_PROD }}
          NX_CHAT_APP_FCM_VAPID_KEY: ${{ secrets.NX_CHAT_APP_FCM_VAPID_KEY_PROD }}
          NX_CHAT_APP_API_TENOR_KEY: ${{ secrets.NX_CHAT_APP_API_TENOR_KEY_PROD }}
          NX_CHAT_APP_API_CLIENT_KEY_CUSTOM: ${{ secrets.NX_CHAT_APP_API_CLIENT_KEY_CUSTOM_PROD }}
          NX_CHAT_SENTRY_DNS: ${{ secrets.NX_CHAT_SENTRY_DNS_PROD }}
          NX_CHAT_APP_ANNONYMOUS_USER_ID: ${{ secrets.NX_CHAT_APP_ANNONYMOUS_USER_ID_PROD }}
          NX_CHAT_APP_NOTIFICATION_WS_URL: ${{ secrets.NX_CHAT_APP_NOTIFICATION_WS_URL_PROD }}
          NX_CHAT_SENTRY_DSN: ${{ secrets.NX_CHAT_SENTRY_DSN_PROD }}

      - name: Compress build artifact
        run: |
          echo "Compress Artifact"
          cd ./dist/apps/chat/
          zip -r mezon-fe-prod.zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mezon-fe-prod
          path: ./dist/apps/chat/mezon-fe-prod.zip
          retention-days: 1

  deploy:
    runs-on: mezon-fe-prod
    name: Deploy Mezon FE
    environment: prod
    needs:
      - build
    steps:
      - name: Clear www folder
        run: |
          echo "Clearing /var/www/mezon-fe/"
          rm -rf /var/www/mezon-fe/*

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: mezon-fe-prod
          path: /var/www/mezon-fe/

      - name: Extract and check files
        run: |
          cd /var/www/mezon-fe/
          ls -la
          unzip mezon-fe-prod.zip

